# Autostart
exec-once = hyprctl setcursor ComixCursors-Opaque-White 24
exec-once = waybar
exec-once = swaybg -i ~/Pictures/walls/wallpaper_parca.jpg -o * -m fill
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store