# Decoration configuration
decoration {
    rounding = 12
    active_opacity = 0.97
    inactive_opacity = 0.97
    
    blur {
        enabled = true
        size = 8
    }
    
    shadow {
        enabled = true
    }
}