# Hyprland Main Config
# Modular config - source all config files

monitor = eDP-1, 1920x1200@60, 0x0, 1, 

source = $HOME/.config/hypr/variables.conf
source = $HOME/.config/hypr/binds.conf
source = $HOME/.config/hypr/window.conf
source = $HOME/.config/hypr/decoration.conf
source = $HOME/.config/hypr/animations.conf
source = $HOME/.config/hypr/miscellaneous.conf
source = $HOME/.config/hypr/autostart.conf
