# Input configuration
input {
    kb_layout = us
    follow_mouse = true
    mouse_refocus = true
    sensitivity = 0

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

# Miscellaneous
misc = {}

# Layout configuration
dwindle {
    pseudotile = true
    preserve_split = true
}