# Window configuration
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class blueman-manager
windowrule = float on, match:title Picture-in-Picture

# Group configuration
group = enabled
bind = $mainMod, G, togglegroup
bind = $mainMod, tab, changegroupactive, f
bind = $mainMod SHIFT, tab, changegroupactive, b